### ISSUE TITLE
Openwrt mips_24kc support

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#1]
感谢您的编译版本和luci。

能否请编译一个mips_24kc的版本。

谐谑。

**Comment by vernesong** [comment]
[clash-linux-mips-softfloat-v0.14.0.gz](https://github.com/Dreamacro/clash/releases/download/v0.14.0/clash-linux-mips-softfloat-v0.14.0.gz)
[clash-linux-mips-hardfloat-v0.14.0.gz](https://github.com/Dreamacro/clash/releases/download/v0.14.0/clash-linux-mips-hardfloat-v0.14.0.gz)
