### ISSUE TITLE
config.yml的设置问题

### ISSUE THREAD

**Issue by vernesong** [frainzy1477/clash#1]
你好，我编译后已能正常运行，服务器日志正常，但无法打开墙外网站，填入RESTful API 的监控端口后也无法登陆管理页面。能否上传config.yml的模板文件供参考呢？

**Comment by frainzy1477** [comment]
我的 config.yml  https://github.com/frainzy1477/clash/blob/master/config.yml
这个 https://github.com/frainzy1477/clash/blob/master/config_2.yml  也可以用
重命名到config.yml
