### ISSUE TITLE
斐讯K3上用不了

### ISSUE THREAD

**Issue by dickwu** [frainzy1477/clash#10]
Phicomm K3
架构	ARMv7 Processor rev 0 (v7l)
固件版本	OpenWrt R9.4.2 By Lean / LuCI openwrt-18.06 branch (git-19.079.57770-b99e77d)

log:
nohup: failed to run command ‘/etc/clash/clash’: No such file or directory

**Comment by frainzy1477** [comment]
你要安装clash

**Comment by frainzy1477** [comment]
> Phicomm K3
> 架构	ARMv7 Processor rev 0 (v7l)
> 固件版本	OpenWrt R9.4.2 By Lean / LuCI openwrt-18.06 branch (git-19.079.57770-b99e77d)
> 
> log:
> nohup: failed to run command ‘/etc/clash/clash’: No such file or directory

你要安装clash的ipk，你安装的是luci-app-clash 和 luci-1i8n-clash-zh-cn ipk
