### ISSUE TITLE
这个错误是不是缺少 armv7 ？

### ISSUE THREAD

**Issue by laincat** [frainzy1477/clash#10]
> make[3]: Entering directory '/home/laincat/Downloads/coolsnowwolf/package/lean/clash'
> mkdir -p /home/laincat/Downloads/coolsnowwolf/dl
> SHELL= flock /home/laincat/Downloads/coolsnowwolf/tmp/.clash-linux-armv6-v0.14.0.gz.flock -c '          /home/laincat/Downloads/coolsnowwolf/scripts/download.pl "/home/laincat/Downloads/coolsnowwolf/dl" "clash-linux-armv6-v0.14.0.gz" "x" "" "https://github.com/Dreamacro/clash/releases/download/v0.14.0/"    '
> Cannot find appropriate hash command, ensure the provided hash is either a MD5 or SHA256 checksum.
> make[3]: *** [Makefile:58: /home/laincat/Downloads/coolsnowwolf/dl/clash-linux-armv6-v0.14.0.gz] Error 255
> make[3]: Leaving directory '/home/laincat/Downloads/coolsnowwolf/package/lean/clash'
> time: package/lean/clash/compile#0.10#0.05#0.15
> make[2]: *** [package/Makefile:109: package/lean/clash/compile] Error 2
> make[2]: Leaving directory '/home/laincat/Downloads/coolsnowwolf'
> make[1]: *** [package/Makefile:103: /home/laincat/Downloads/coolsnowwolf/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
> make[1]: Leaving directory '/home/laincat/Downloads/coolsnowwolf'
> make: *** [/home/laincat/Downloads/coolsnowwolf/include/toplevel.mk:218：world] 错误 2

**Comment by zcracker** [comment]
手动下载clash-linux-armv6-v0.14.0.gz放到dl目录下

**Comment by laincat** [comment]
> 手动下载clash-linux-armv6-v0.14.0.gz放到dl目录下

噢，好。
