### ISSUE TITLE
请问，配置以哪个为准？

### ISSUE THREAD

**Issue by laincat** [frainzy1477/clash#11]
目前使用上的一些逻辑没明白。
1. 配置文件 config.yml 内哪些设置是被 Luci 接管了？
2. 哪些内容需要一一对应设置？
3. 虽然有些可以通过测试看出来，不过有些看不出来，无法调试出结论。

感谢大大。

**Comment by vernesong** [comment]
luci上你能看到的信息，包括转发端口，dashboard密码、登录端口等，以及使用clash转发dns时会看情况更改一下监听端口和nameserver信息，目的只是便于直接使用和防止冲突。
