### ISSUE TITLE
自定义DNS

### ISSUE THREAD

**Issue by happy-proxy** [frainzy1477/clash#11]
请问自定义DNS填入的参数是会覆盖config.yml中的设置吗，还是优先读取config.yml中的设置？

另外，Clash控制面板无法打开，显示如下：
![](http://ww1.sinaimg.cn/large/006tNc79ly1g3mq7lwz9qj308c023mx8.jpg)

**Comment by frainzy1477** [comment]
> 请问自定义DNS填入的参数是会覆盖config.yml中的设置吗，还是优先读取config.yml中的设置？
> 
> 另外，Clash控制面板无法打开，显示如下：
> ![](https://camo.githubusercontent.com/5053fd40668969fac2717eaa7433abac076dd5cf/687474703a2f2f7777312e73696e61696d672e636e2f6c617267652f303036744e6337396c793167336d71376c777a39716a333038633032336d78382e6a7067)

会覆盖config.yml dns
登录密码123456 ， 端口9090 主机名=不是127.0.0.1， 是你的路由器登录地址


![image](https://user-images.githubusercontent.com/49537471/58759266-b793a180-8559-11e9-9faa-9fee73c292dd.png)

**Comment by happy-proxy** [comment]
我当然知道是路由器的地址，而且另一个Yacd控制界面加载没有问题。

![](http://ww4.sinaimg.cn/large/006tNc79ly1g3mywbizgoj30bm03b0sz.jpg)

**Comment by happy-proxy** [comment]
找到症结了，第一次输入密码的时候输入错误，此后页面不提示重新登录

清除缓存就OK

诡异，完
