### ISSUE TITLE
你的示例用的皮肤是哪一家的？

### ISSUE THREAD

**Issue by qinfeng8848** [frainzy1477/clash#12]
你的示例用的皮肤是哪一家的？是网件的吗？

**Comment by frainzy1477** [comment]
> 你的示例用的皮肤是哪一家的？是网件的吗？

https://github.com/frainzy1477/clash/releases/download/v0.14.0_Luci/luci-theme-rosy_git-19.109.76350-a9b9c30-1_all.ipk
