### ISSUE TITLE
v2ray／SS 节点订阅支持

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#12]
请问会加入v2ray／SS 节点订阅支持么？谢谢。

**Comment by frainzy1477** [comment]
> 请问会加入v2ray／SS 节点订阅支持么？谢谢。

支持

**Comment by gitx6** [comment]
当前版本就支持？我试一下。

**Comment by frainzy1477** [comment]
> 当前版本就支持？我试一下。

从0.13都支持

**Comment by gitx6** [comment]
支持的是config.yml文件的托管。不是类似SSR／SSD／SS的服务器节点订阅吧？

**Comment by gitx6** [comment]
能否像‘自定义DNS’功能一样，从SS服务器订阅节点ss://Y2hhY.......
