### ISSUE TITLE
在luci界面,取消启动clash的勾选项,点保存应用,程序并不会停止

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#13]
在luci界面,取消启动clash的勾选项,点保存应用,程序并不会停止

**Comment by gitx6** [comment]
页面没刷新？

**Comment by zcracker** [comment]
刷新过了
还有个问题是
Mem: 103372K used, 407568K free, 2084K shrd, 9252K buff, 36504K cached
CPU:   3% usr   1% sys   0% nic  94% idle   0% io   0% irq   0% sirq
Load average: 0.02 0.02 0.00 1/97 12706
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
11775     1 root     S    ###  790m 158%   2% /etc/clash/clash -d /etc/clash

clash 虚拟内存占用太高了,一阵就上不去了

**Comment by zcracker** [comment]
11775 root      790m S    /etc/clash/clash -d /etc/clash
11965 dnsmasq   2464 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf.cfg01411c -k -x /var/run/dnsmasq/dnsmasq.cfg01411c.pid
11984 root      1188 S    /bin/sh /etc/rc.common /etc/init.d/clash running
11988 root      1056 S    flock 1000
12032 root         0 IW   [kworker/1:3]
12074 root      1188 S    /bin/sh /etc/rc.common /etc/init.d/clash restart
12078 root      1056 S    flock 1000
12789 root      1188 S    /bin/sh /etc/rc.common /etc/init.d/clash restart
12793 root      1056 S    flock 1000
12815 root      1188 S    /bin/sh /etc/rc.common /etc/init.d/clash restart
12819 root      1056 S    flock 1000
13123 root      1188 S    /bin/sh /etc/rc.common /etc/init.d/clash restart

**Comment by gitx6** [comment]
最新luci测试，没有你所说的问题。
