### ISSUE TITLE
我使用https://github.com/coolsnowwolf/openwrt编译的Newifi d2安装你提供的ipk出错

### ISSUE THREAD

**Issue by qinfeng8848** [frainzy1477/clash#14]
我使用https://github.com/coolsnowwolf/openwrt  编译的Newifi d2安装你提供的ipk出错
root@OpenWrt:/tmp# opkg install clash_0.14.0_mipsel_24kc.ipk
Installing clash (0.14.0) to root...
Collected errors:
 * verify_pkg_installable: Only have 0kb available on filesystem /overlay, pkg clash needs 2945
 * opkg_install_cmd: Cannot install package clash.

**Comment by frainzy1477** [comment]
> 我使用https://github.com/coolsnowwolf/openwrt 编译的Newifi d2安装你提供的ipk出错
> root@OpenWrt:/tmp# opkg install clash_0.14.0_mipsel_24kc.ipk
> Installing clash (0.14.0) to root...
> Collected errors:
> 
> * verify_pkg_installable: Only have 0kb available on filesystem /overlay, pkg clash needs 2945
> * opkg_install_cmd: Cannot install package clash.

设备上的存储空间不足    * verify_pkg_installable: Only have 0kb available on filesystem /overlay, pkg clash needs 2945
