### ISSUE TITLE
通过luci打开代理后，系统中出现多个clash进程

### ISSUE THREAD

**Issue by KangKai1982** [frainzy1477/clash#16]
如题，系统中出现多个clash进程
log中多个进程冲突，出现bind error address already in use

在控制台中执行
/etc/init.d/clash start
却正常只出现一个进程
但是脚本有报错

> sh: 127.0.0.1#5333: unknown operand
uci: Entry not found

**Comment by frainzy1477** [comment]
> 如题，系统中出现多个clash进程
> log中多个进程冲突，出现bind error address already in use
> 
> 在控制台中执行
> /etc/init.d/clash start
> 却正常只出现一个进程
> 但是脚本有报错
> 
> > sh: 127.0.0.1#5333: unknown operand
> > uci: Entry not found

你用是0.16.0？

**Comment by KangKai1982** [comment]
@frainzy1477 是的，安装的luci-app-clash_0.16.0-1_all.ipk和它对应的语言包，clash主程序安装的你网站上的14.0的包。

**Comment by frainzy1477** [comment]
> @frainzy1477 是的，安装的luci-app-clash_0.16.0-1_all.ipk和它对应的语言包，clash主程序安装的你网站上的14.0的包。

![image](https://user-images.githubusercontent.com/49537471/57685159-dc3ade80-7669-11e9-8fa6-4ba2735c009a.png)
我自己试试没有问题

**Comment by frainzy1477** [comment]
> @frainzy1477 是的，安装的luci-app-clash_0.16.0-1_all.ipk和它对应的语言包，clash主程序安装的你网站上的14.0的包。

试试 0.17.0吧

**Comment by KangKai1982** [comment]
实用luci web端启动clash，出现两个clash进程

使用service clash start启动，正常没有多余进程，干脆在clash start前加一个killall clash算了

**Comment by frainzy1477** [comment]
> 实用luci web端启动clash，出现两个clash进程
> 
> 使用service clash start启动，正常没有多余进程，干脆在clash start前加一个killall clash算了

![image](https://user-images.githubusercontent.com/49537471/57686340-0097ba80-766c-11e9-99ed-4e2adcc54343.png)
我也用luci web端启动clash没有问题哦

**Comment by KangKai1982** [comment]
好吧，我自己再摸索一下，不管他了
