### ISSUE TITLE
如何让路由器自身流量翻墙？

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#16]
如何让路由器自身流量翻墙？

**Comment by tony1016** [comment]
涉及到output链的处理，因为clash目前没有办法打标记，估计还得依靠ipset和chnroute

**Comment by tony1016** [comment]
看到一种合适的做法，用另外一个用户启动clash，然后通过match owner去匹配，如果是clash的流量就return，其他output流量全部redir到clash
