### ISSUE TITLE
建议添加日志自动/手动清理功能

### ISSUE THREAD

**Issue by laoz77** [frainzy1477/clash#19]
开发者您好！
我是用自建的服务器，运行一两天之后会出现断流的情况。看日志里有很多记录，不知道是不是因为日志太多引起clash崩溃。建议添加日志自动清理和手动清理功能，也建议有选项让使用者决定是不是要记录日志。谢谢！

**Comment by frainzy1477** [comment]
重新启动或停止后日志自动清理, 如果启用自动更新每天自动重启

**Comment by frainzy1477** [comment]
> 开发者您好！
> 我是用自建的服务器，运行一两天之后会出现断流的情况。看日志里有很多记录，不知道是不是因为日志太多引起clash崩溃。建议添加日志自动清理和手动清理功能，也建议有选项让使用者决定是不是要记录日志。谢谢！
重新启动或停止后日志自动清理, 如果启用自动更新每天自动重启

**Comment by laoz77** [comment]
谢谢您的解释。
这个自动更新的功能在使用自建服务器的时候有些问题：启动自动更新会从空白的订阅地址下载空白的配置文件替换已经存在的配置文件，从而导致clash无法运行。因此自建服务器只能关闭自动更新。
如果能添加选项由用户选择时候创建日志或者自动清理日志可以避免下载空白配置文件或者因日志过多导致崩溃。

关于下载空白配置文件的复现：
将订阅URL留空并点击更新配置文件，这时配置文件从用户原来上传的可用文件变成空白文件。

**Comment by frainzy1477** [comment]
> 谢谢您的解释。
> 这个自动更新的功能在使用自建服务器的时候有些问题：启动自动更新会从空白的订阅地址下载空白的配置文件替换已经存在的配置文件，从而导致clash无法运行。因此自建服务器只能关闭自动更新。
> 如果能添加选项由用户选择时候创建日志或者自动清理日志可以避免下载空白配置文件或者因日志过多导致崩溃。
> 
> 关于下载空白配置文件的复现：
> 将订阅URL留空并点击更新配置文件，这时配置文件从用户原来上传的可用文件变成空白文件。

luci更新了

**Comment by laoz77** [comment]
谢谢您！
