### ISSUE TITLE
不明白缺了什么。

### ISSUE THREAD

**Issue by laincat** [frainzy1477/clash#2]
> 
> /usr/lib/lua/luci/dispatcher.lua:509: Failed to execute cbi dispatcher target for entry '/admin/services/clash/config'.
> The called action terminated with an exception:
> /usr/lib/lua/luci/model/cbi/clash/config.lua:9: module 'luci.fs' not found:
> 	no field package.preload['luci.fs']
> 	no file './luci/fs.lua'
> 	no file '/usr/share/lua/luci/fs.lua'
> 	no file '/usr/share/lua/luci/fs/init.lua'
> 	no file '/usr/lib/lua/luci/fs.lua'
> 	no file '/usr/lib/lua/luci/fs/init.lua'
> 	no file './luci/fs.so'
> 	no file '/usr/lib/lua/luci/fs.so'
> 	no file '/usr/lib/lua/loadall.so'
> 	no file './luci.so'
> 	no file '/usr/lib/lua/luci.so'
> 	no file '/usr/lib/lua/loadall.so'
> stack traceback:
> 	[C]: in function 'assert'
> 	/usr/lib/lua/luci/dispatcher.lua:509: in function 'dispatch'
> 	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

点“服务器配置”就提示这个。。。

**Comment by frainzy1477** [comment]
你要用 https://github.com/coolsnowwolf/lede 编译固件，  还是在/usr/lib/lua/luci/model/cbi/clash/config.lua:9 修改吧
![Screenshot_3](https://user-images.githubusercontent.com/49537471/56881260-70b21800-6a92-11e9-9676-a62d5e8f643d.png)
如果有这个https://github.com/frainzy1477/clash/issues/3 问题   安装 coreutils-nohup。

**Comment by laincat** [comment]
好的，我现在就去试试

**Comment by laincat** [comment]
安装了 coreutils-nohup，并且也是用的 Lean 的源码编译的固件。

> /usr/lib/lua/luci/dispatcher.lua:509: Failed to execute cbi dispatcher target for entry '/admin/services/clash/config'.
> The called action terminated with an exception:
> /usr/lib/lua/luci/model/cbi/clash/config.lua:9: module 'luci.fs' not found:
> 	no field package.preload['luci.fs']
> 	no file './luci/fs.lua'
> 	no file '/usr/share/lua/luci/fs.lua'
> 	no file '/usr/share/lua/luci/fs/init.lua'
> 	no file '/usr/lib/lua/luci/fs.lua'
> 	no file '/usr/lib/lua/luci/fs/init.lua'
> 	no file './luci/fs.so'
> 	no file '/usr/lib/lua/luci/fs.so'
> 	no file '/usr/lib/lua/loadall.so'
> 	no file './luci.so'
> 	no file '/usr/lib/lua/luci.so'
> 	no file '/usr/lib/lua/loadall.so'
> stack traceback:
> 	[C]: in function 'assert'
> 	/usr/lib/lua/luci/dispatcher.lua:509: in function 'dispatch'
> 	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by frainzy1477** [comment]
我重新编译了
