### ISSUE TITLE
Clash报错

### ISSUE THREAD

**Issue by john-lo7798** [frainzy1477/clash#2]
FATA[0000] Parse config error: open /etc/clash/config.yml/config.yml: not a directory 

time="2019-05-22T21:04:35Z" level=fatal msg="Parse config error: Configuration file /etc/clash/config.yml is empty"

编辑 config.yml 加上内容 ./clash -d /etc/clash/  后正常运行。

**Comment by frainzy1477** [comment]
是你的config.yml问题， 我正常运行没有什么问题

**Comment by frainzy1477** [comment]
> FATA[0000] Parse config error: open /etc/clash/config.yml/config.yml: not a directory

FATA[0000] Parse config error: open /etc/clash/config.yml/config.yml: not a directory 这是错的
必须 /etc/clash/config.yml
