### ISSUE TITLE
luci v0.15.0 clash 控制面板无法打开

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#21]
提示：
打不开页面192.168.1.1:undefined/ui，因为该页面地址无效。

此问题是更新版本后出现的

**Comment by frainzy1477** [comment]
> 提示：
> 打不开页面192.168.1.1:undefined/ui，因为该页面地址无效。
> 
> 此问题是更新版本后出现的

我自己没有这个问题， 设置端口了吗?

**Comment by gitx6** [comment]
直接覆盖安装的。设置-控制面板端口 有9090

**Comment by frainzy1477** [comment]
> 直接覆盖安装的。设置-控制面板端口 有9090

在设置修改端口试试吧

**Comment by gitx6** [comment]
修改端口没有作用。主页面显示：

Dashboard Hostname - 未设置 
Dashboard Port - 未设置
Dashboard Secret- 未设置

**Comment by frainzy1477** [comment]
> 修改端口没有作用。主页面显示：
> 
> Dashboard Hostname - 未设置
> Dashboard Port - 未设置
> Dashboard Secret- 未设置

怎么可能， 你在用OP是那个本版？lean的？

**Comment by frainzy1477** [comment]
> > 修改端口没有作用。主页面显示：
> > Dashboard Hostname - 未设置
> > Dashboard Port - 未设置
> > Dashboard Secret- 未设置
> 
> 怎么可能， 你在用OP是那个本版？lean的？

![image](https://user-images.githubusercontent.com/49537471/59245473-8f87fa80-8c4b-11e9-979c-e736cebeefc1.png)

**Comment by gitx6** [comment]
对，这三个信息都没有。

之前的版本clash控制面板连接还没问题。我删除重新安装，也是同样问题。

**Comment by frainzy1477** [comment]
> 对，这三个信息都没有。
> 
> 之前的版本clash控制面板连接还没问题。我删除重新安装，也是同样问题。
 那个路由器 ？？

**Comment by frainzy1477** [comment]
重新下载ipk试试

我在用的OP本版  Powered byLuCI Master (git-19.121.62139-9ee402e) / OpenWrt R9.5.1 By Lean 没有问题

**Comment by gitx6** [comment]
Powered by LuCI Master (git-19.115.08622-59e4954) / OpenWrt R9.5.1 By Lean

**Comment by frainzy1477** [comment]
> Powered by LuCI Master (git-19.115.08622-59e4954) / OpenWrt R9.5.1 By Lean

那个路由器 ,新三？

**Comment by gitx6** [comment]
X86_64

重新下载，安装，重启路由器。

问题解决。
