### ISSUE TITLE
客户端访问控制功能

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#23]
能否增加客户端访问控制功能。指定客户端IP地址全局或者直连

**Comment by frainzy1477** [comment]
> 能否增加客户端访问控制功能。指定客户端IP地址全局或者直连

https://github.com/frainzy1477/clash/releases/tag/v0.17.0

**Comment by gitx6** [comment]
SOURCE-IP-CIDR

**Comment by gitx6** [comment]
`-` SRC-IP-CIDR 192.168.0.1/32, DIRECT
