### ISSUE TITLE
访问luci页面时系统日志出现大量错误

### ISSUE THREAD

**Issue by shikkoku** [frainzy1477/clash#24]
当打开clash的设置页面，路由系统日志就会出现大量这种提示

系统版本 OpenWrt R9.6.1 / LuCI Master (git-19.146.62144-fd6fdb2)

设备型号 Newifi-D1

Fri Jun 14 13:17:58 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:17:59 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:00 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:01 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:02 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:03 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:04 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:05 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:06 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:07 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:08 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:09 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:10 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:11 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:12 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:13 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:14 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:15 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:16 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:17 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:18 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:19 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:20 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:21 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:22 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:23 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:24 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:25 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:26 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:27 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:28 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:29 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:30 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:31 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:32 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:33 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:34 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:35 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:36 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:37 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:38 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:39 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:40 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:41 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:42 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:43 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:44 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:45 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:46 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:47 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:48 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:49 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:50 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:51 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:52 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:53 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:54 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:55 2019 daemon.err uhttpd[2052]: uci: Entry not found
Fri Jun 14 13:18:56 2019 daemon.err uhttpd[2052]: uci: Entry not found

**Comment by frainzy1477** [comment]
> daemon.err uhttpd[2052]: uci: Entry not found

这问题没看过了， 可能是mwan还是dns问题。试试0.14.0 的luci 看看

**Comment by shikkoku** [comment]
> > daemon.err uhttpd[2052]: uci: Entry not found
> 
> 这问题没看过了， 可能是mwan还是dns问题。试试0.14.0 的luci 看看

只有访问clash的设置页面才会出现这些日志，不访问不会增加记录。mwan我已经移除软件包了。

**Comment by shikkoku** [comment]
呃，用在x86的软路由上没复现这种情况，奇怪。

OpenWrt R9.6.1 / LuCI Master (git-19.146.62144-fd6fdb2)


软路由的内核版本是4.9.180

newifi-d1的内核版本是4.14

两台设备都是新装的系统。

**Comment by shikkoku** [comment]
已找到原因，我的两台路由都是用作辅助（旁路）网关，其中有问题那台的LAN口设置成了DHCP客户端协议，没有问题的那台是静态IP。设置回静态IP后问题消失，LAN口使用DHCP客户端协议会导致clash设置界面中的Dashboard Hostname项目无法正常显示。
