### ISSUE TITLE
clash与dnsmasq的关系？

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#25]
请问作者，clash与dnsmasq的关系？，是否需要设置那里？开启clash，dns就解析失败，上不去网了，谢谢，幸苦了

**Comment by frainzy1477** [comment]
> 请问作者，clash与dnsmasq的关系？，是否需要设置那里？开启clash，dns就解析失败，上不去网了，谢谢，幸苦了

不需要需要设置，可能是你的config.yml dns 问题 试试0.17.0 你要开自定义DNS

**Comment by gitx6** [comment]
clash配置文件可以自带dns解析

> dns:
>  enable: true
>  listen: 0.0.0.0:5353
> enhanced-mode: redir-host
>  #fake-ip-range: 198.18.0.1/16
> nameserver:
> - tls://dns.rubyfish.cn:853 
> fallback:
> - tls://8.8.8.8:853 
>  - tls://1.1.1.1:853
