### ISSUE TITLE
国外网IP在clash启动后，保持国内ip

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#26]
国外网IP在clash启动后保持为国内解析，而且显示外网无法访问。但实际已经可以访问。

> 客户端 | 运行中

> 国外网IP  : 116.231.36.122 China Telecom

> 国内网IP  : 116.231.36.122 中国 电信

> 谷歌网 : 无法访问 | Youtube网  : 无法访问

**Comment by frainzy1477** [comment]
> 国外网IP在clash启动后保持为国内解析，而且显示外网无法访问。但实际已经可以访问。
> 
> > 客户端 | 运行中
> 
> > 国外网IP  : 116.231.36.122 China Telecom
> 
> > 国内网IP  : 116.231.36.122 中国 电信
> 
> > 谷歌网 : 无法访问 | Youtube网  : 无法访问

启用仅选择局域网IP只走代理了没？

**Comment by gitx6** [comment]
启用了。也就是说路由器自身流量没有出国造成的？那么回到之前的issue，有方法让路由器自身流量出国么？

**Comment by frainzy1477** [comment]
> 启用了。也就是说路由器自身流量没有出国造成的？那么回到之前的issue，有方法让路由器自身流量出国么？

可能你选择ip走代理错，我这边没有啥问题

**Comment by frainzy1477** [comment]
![Screenshot_20190616-001649_1](https://user-images.githubusercontent.com/49537471/59553758-4083f180-8fcc-11e9-8635-afd2aa272782.jpg)

我选择电脑和两个手机的lan IP能走代理，其他lan ip不会走代理

**Comment by gitx6** [comment]
能增加不走代理的局域网IP么？

**Comment by frainzy1477** [comment]
> 能增加不走代理的局域网IP么？

https://github.com/frainzy1477/clash/releases/tag/v0.18.0
