### ISSUE TITLE
luci对config.yml中的注释行（#）的处理

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#27]
隐约觉得在 config.yml 如果Proxy Group段有多行，且用#注释当中的某几行，在luci中并未过滤注释行。因为我发现IP在不断的跳，在只有一行的记录下才能稳定。clash dashboard此时也只显示一组ip

**Comment by frainzy1477** [comment]
> 隐约觉得在 config.yml 如果Proxy Group段有多行，且用#注释当中的某几行，在luci中并未过滤注释行。因为我发现IP在不断的跳，在只有一行的记录下才能稳定。clash dashboard此时也只显示一组ip

不是luci的问题， 你自己要看看你的config.yml吧
