### ISSUE TITLE
clash-0.19.0的源码版本号如下并未变更

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#29]
PKG_NAME:=luci-app-clash
PKG_VERSION:=0.18.0
PKG_RELEASE:=2
PKG_MAINTAINER:=frainzy1477

**Comment by frainzy1477** [comment]
> PKG_NAME:=luci-app-clash
> PKG_VERSION:=0.18.0
> PKG_RELEASE:=2
> PKG_MAINTAINER:=frainzy1477

源代码还没有更新
