### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by lwsJ** [frainzy1477/clash#3]
不知道为什么会提示以下错误信息，能麻烦帮忙看一下吗？用的是lean编译版
nohup: failed to run command ‘/etc/clash/clash’: No such file or directory

**Comment by frainzy1477** [comment]
在/etc/clash/ 里面你没有安装clash的ipk, 必须要安装吧。你也可以从dreamaco repo 下载linux-clash-*重命名到clash 然后上传到/etc/clash/

**Comment by lwsJ** [comment]
麻烦能再说具体些吗？是否 luci-app-clash_2.2b-1_all.ipk 这个 安装包 要在/etc/clash/ 里面再安装一次呢？
dreamaco repo 下载clash-linux-386-v0.14.0.gz 重命名到clash 然后上传到/etc/clash/  能说具体些吗？

**Comment by gitx6** [comment]
假设你是用X86_64

$ wget -q- https://github.com/frainzy1477/clash/releases/download/v0.14.0/clash_0.14.0_x86_64.ipk
$ wget -q- https://github.com/frainzy1477/clash/releases/download/v2.2b/luci-app-clash_2.2b-1_all.ipk
$ opkg install clash_0.14.0_x86_64.ipk
$ opkg install luci-app-clash_2.2b-1_all.ipk

enjoy.

**Comment by lwsJ** [comment]
谢谢！已经解决。
