### ISSUE TITLE
日志显示/etc/rc.common: line 280: nohup: not found

### ISSUE THREAD

**Issue by chocksyu** [frainzy1477/clash#3]
您好！
    使用设备为nano neo2 pi ，配置文件直接从clash for Windows修改后调入，点击启动后日志显示“/etc/rc.common: line 280: nohup: not found”，请问是什么问题呢？
    谢谢！

**Comment by frainzy1477** [comment]
你要用 https://github.com/coolsnowwolf/lede 编译固件

**Comment by chocksyu** [comment]
感谢您的回复，我重新编译一下，谢谢

**Comment by frainzy1477** [comment]
可以安装  coreutils-nohup

**Comment by chocksyu** [comment]
安装coreutils-nohup后成功启动！
不过又有了一个新的问题想请教您一下：启动成功后，访问国内网站正常，但是被墙网站仍无法访问，查看日志没有被墙网站解析记录。但在设备浏览器上使用SwitchyOmega等插件，指定到clash的socks端口是可以访问的，日志中也正常有记录。请问我在openwrt中需要更改哪些设置？

**Comment by chocksyu** [comment]
搞定了大佬，由clash监听53端口，将Dnsmasq 的端口改成其他的

**Comment by frainzy1477** [comment]
不需要改什么clash听5354端口,Dnsmasq的端口不要改

**Comment by zxlhhyccc** [comment]
> 不需要改什么clash听5354端口,Dnsmasq的端口不要改

大佬您好，请问配置文件格式是什么样子的？！

**Comment by frainzy1477** [comment]
配置文件格式和源的相同，你不需要修改什么。所需的任何更改都将是自动的

**Comment by frainzy1477** [comment]
> > 不需要改什么clash听5354端口,Dnsmasq的端口不要改
> 
> 大佬您好，请问配置文件格式是什么样子的？！

配置文件格式和源的相同，你不需要修改什么。所需的任何更改都将是自动的
