### ISSUE TITLE
DNS解析问题

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#31]
clash运行后总有以下错误
app store无法下载文件，貌似是dns解析问题，配置如下
---
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: warning
external-controller: 0.0.0.0:9090
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: redir-host
  nameserver:
  - 1.2.4.8
  - 101.6.6.6
  - 117.50.10.10
  - 119.29.29.29
  - 223.5.5.5
  - tls://dns.rubyfish.cn:853
  fallback:
  - tls://1.1.1.1:853
  - tls://1.0.0.1:853
  - tls://dns.google:853
经过仔细查看，connect: connection refused应该是回程链接失败

error: dial tcp 153.37.208.8:80: i/o timeout"  这个暂时不知是什么原因

**Comment by frainzy1477** [comment]
> ## clash运行后总有以下错误
> app store无法下载文件，貌似是dns解析问题，配置如下
> port: 7890
> socks-port: 7891
> allow-lan: true
> mode: Rule
> log-level: warning
> external-controller: 0.0.0.0:9090
> dns:
> enable: true
> ipv6: false
> listen: 0.0.0.0:5353
> enhanced-mode: redir-host
> nameserver:
> 
> * 1.2.4.8
> * 101.6.6.6
> * 117.50.10.10
> * 119.29.29.29
> * 223.5.5.5
> * tls://dns.rubyfish.cn:853
>   fallback:
> * tls://1.1.1.1:853
> * tls://1.0.0.1:853
> * tls://dns.google:853
> 
> time="2019-06-23T06:00:29Z" level=warning msg="Proxy[DIRECT] connect [36.48.110.77 --> 139.227.8.102] error: dial tcp 139.227.8.102:17457: connect: connection refused"
> time="2019-06-23T06:00:30Z" level=info msg="111.222.81.96 --> 139.227.8.102 match GEOIP using DIRECT"
> time="2019-06-23T06:00:30Z" level=warning msg="Proxy[DIRECT] connect [111.222.81.96 --> 139.227.8.102] error: dial tcp 139.227.8.102:1068: connect: connection refused"
> time="2019-06-23T06:00:30Z" level=info msg="111.222.81.96 --> 139.227.8.102 match GEOIP using DIRECT"
> time="2019-06-23T06:00:30Z" level=warning msg="Proxy[DIRECT] connect [111.222.81.96 --> 139.227.8.102] error: dial tcp 139.227.8.102:17457: connect: connection refused"
> time="2019-06-23T06:00:30Z" level=warning msg="Proxy[DIRECT] connect [10.0.0.235 --> 101.224.45.11] error: dial tcp 101.224.45.11:1094: i/o timeout"
> time="2019-06-23T06:00:30Z" level=warning msg="Proxy[DIRECT] connect [10.0.0.235 --> 112.11.59.52] error: dial tcp 112.11.59.52:62512: i/o timeout"
> time="2019-06-23T06:00:30Z" level=warning msg="Proxy[DIRECT] connect [10.0.0.235 --> 61.132.63.86] error: dial tcp 61.132.63.86:50000: i/o timeout"

不要开DNS转发， 试试这个
dns:
  enable: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:5353
  nameserver:
   - tls://dns.rubyfish.cn:853  
   - 119.29.29.29 
   - 101.132.183.99
   - 114.114.115.115
   - 114.114.114.114
   - 223.5.5.5    
  fallback:
   - tls://dns.google:853 
   - tls://1.1.1.1:853

**Comment by zcracker** [comment]
经过仔细查看，connect: connection refused应该是回程链接失败
error: dial tcp 153.37.208.8:80: i/o timeout" 这个暂时不知是什么原因

**Comment by frainzy1477** [comment]
> 经过仔细查看，connect: connection refused应该是回程链接失败
> error: dial tcp 153.37.208.8:80: i/o timeout" 这个暂时不知是什么原因
就是超时吧， 这个不是luci问题
