### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by hackenfu** [frainzy1477/clash#35]
本来我是从0.19升级到0.20的，结果upgrading。。。一直就没反应了。于是remove clash和luci，重新安装clash没问题，luci0.20遇到以下问题：
root@OpenWrt:~# opkg install /tmp/luci-app-clash_0.20.0-1_all.ipk
Installing luci-app-clash (0.20.0-1) to root...
Collected errors:
 * check_data_file_clashes: Package luci-app-clash wants to install file /usr/share/clash/clash_version
        But that file is already provided by package  * clash
 * opkg_install_cmd: Cannot install package luci-app-clash.

**Comment by hackenfu** [comment]
我删除clash先装luci倒是成功了，但是再装clash又是类似的问题，感觉这两者不能共存的？
我一直以为clash和luci必须同时装，一个是软件，一个是界面？看起来好像只需要装luci就行了？

**Comment by hackenfu** [comment]
更新URL托管之后又提示：
nohup: failed to run command ‘/etc/clash/clash’: Permission denied
本来提示没这个文件夹，我新建了clash下面的clash，而且给了777的最大权限，还是提示不行

**Comment by frainzy1477** [comment]
> * /usr/share/clash/clash_version

重新安装先运行命令  rm -rf /usr/share/clash/clash_version

**Comment by frainzy1477** [comment]
> 更新URL托管之后又提示：
> nohup: failed to run command ‘/etc/clash/clash’: Permission denied
> 本来提示没这个文件夹，我新建了clash下面的clash，而且给了777的最大权限，还是提示不行

我自己没有这问题
如果有运行命令  chmod +x /etc/clash/clash

**Comment by hackenfu** [comment]
帮我明确下，是luci和clash都要装吗？还是只需要luci？谢谢老大

**Comment by frainzy1477** [comment]
> 帮我明确下，是luci和clash都要装吗？还是只需要luci？谢谢老大
如果你已经安装 clash的ipk 那不需要再安装
但你remove clash和luci，你必须重新安装clash和luci的ipk

我就更新luci的ipk，所以你要更新luci的ipk ,就卸载luci  opkg remove luci-app-clash。不要卸载 clash
