### ISSUE TITLE
21版本编译失败

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#36]
放到openwrt目录下编译失败，不建议加自动更新啊，万一哪天不可描述原因删库了，就完蛋了，自动更新也成摆设了

**Comment by zcracker** [comment]
cp -fpR /home/zcracker/openwrtv18.06.3/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu /home/zcracker/openwrtv18.06.3/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root.orig-mvebu
/home/zcracker/openwrtv18.06.3/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu/usr/lib/opkg/info/luci-app-clash.postinst-pkg: line 3: /etc/init.d/clash: No such file or directory
postinst script ./usr/lib/opkg/info/luci-app-clash.postinst has failed with exit code 127
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 1
make[2]: Leaving directory '/home/zcracker/openwrtv18.06.3'
package/Makefile:104: recipe for target '/home/zcracker/openwrtv18.06.3/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/stamp/.package_install' failed
make[1]: *** [/home/zcracker/openwrtv18.06.3/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/stamp/.package_install] Error 2

**Comment by frainzy1477** [comment]
> cp -fpR /home/zcracker/openwrtv18.06.3/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu /home/zcracker/openwrtv18.06.3/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root.orig-mvebu
> /home/zcracker/openwrtv18.06.3/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/root-mvebu/usr/lib/opkg/info/luci-app-clash.postinst-pkg: line 3: /etc/init.d/clash: No such file or directory
> postinst script ./usr/lib/opkg/info/luci-app-clash.postinst has failed with exit code 127
> package/Makefile:65: recipe for target 'package/install' failed
> make[2]: *** [package/install] Error 1
> make[2]: Leaving directory '/home/zcracker/openwrtv18.06.3'
> package/Makefile:104: recipe for target '/home/zcracker/openwrtv18.06.3/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/stamp/.package_install' failed
> make[1]: *** [/home/zcracker/openwrtv18.06.3/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/stamp/.package_install] Error 2

if you have a problem compiling, locate error and fix by yourself
