### ISSUE TITLE
clash的日志能不能和syslog日志混一起出现呢？

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#37]
clash的日志能不能和syslog日志混一起出现呢？

**Comment by frainzy1477** [comment]
> clash的日志能不能和syslog日志混一起出现呢？

不能

**Comment by frainzy1477** [comment]
> > clash的日志能不能和syslog日志混一起出现呢？
> 
> 不能

clash的日志 /tmp/clash.log
