### ISSUE TITLE
22版本描述

### ISSUE THREAD

**Issue by hackenfu** [frainzy1477/clash#38]
注意：上传之前，请将配置文件重命名为config.yaml。文件将保存到 /etc/clash
是不是写错了？yaml？

**Comment by frainzy1477** [comment]
> config.yaml

config.yaml

**Comment by frainzy1477** [comment]
> 注意：上传之前，请将配置文件重命名为config.yaml。文件将保存到 /etc/clash
> 是不是写错了？yaml？

没错， 是 config.yaml
https://github.com/frainzy1477/luci-app-clash

**Comment by hackenfu** [comment]
不过我从22版本（clash是15）开始，从URL更新的“配置”栏目里面都是空白的了，不像以前都有内容。但是似乎不影响使用。升级23版本依然如此。
Resolving dler.cloud... 104.31.77.117, 104.31.76.117, 2606:4700:30::681f:4d75, ...
Connecting to dler.cloud|104.31.77.117|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 56487 (55K) [application/octet-stream]
Saving to: '/etc/clash/config.yml'

     0K .......... .......... .......... .......... .......... 90%  117K 0s
    50K .....                                                 100% 26.9M=0.4s

2019-06-30 14:14:47 (129 KB/s) - '/etc/clash/config.yml' saved [56487/56487]
