### ISSUE TITLE
When clash and luci-app-clash are running, the System > Startup page will not load. OpenWrt 18.06.02

### ISSUE THREAD

**Issue by jitdor** [frainzy1477/clash#39]
When clash and luci-app-clash are running, the System > Startup page will not load, and the VM cannot be soft rebooted. No specific errors otherwise. OpenWrt 18.06.02 stock image + clash + luci-app-clash.

**Comment by frainzy1477** [comment]
> When clash and luci-app-clash are running, the System > Startup page will not load, and the VM cannot be soft rebooted. No specific errors otherwise. OpenWrt 18.06.02 stock image + clash + luci-app-clash.

you mean openwrt overview page or clash overview page? i certainly have not experience this problem

**Comment by jitdor** [comment]
> > When clash and luci-app-clash are running, the System > Startup page will not load, and the VM cannot be soft rebooted. No specific errors otherwise. OpenWrt 18.06.02 stock image + clash + luci-app-clash.
> 
> you mean openwrt overview page or clash overview page? i certainly have not experience this problem

OpenWrt overpage is fine. When you visit System > Startup, the page will not load. Both the Clash Dashboard and Yacd Dashboard are fine too. I've just deployed the new 18.06.4 image from scratch (openwrt-18.06.4-x86-64-combined-ext4) and just install the latest clash_0.15.0-1_x86_64 and luci-app-clash_0.24.0-1_all, when Clash is up and running, I can't get to the System > Startup page.

**Comment by alliswell2day** [comment]
> > > When clash and luci-app-clash are running, the System > Startup page will not load, and the VM cannot be soft rebooted. No specific errors otherwise. OpenWrt 18.06.02 stock image + clash + luci-app-clash.
> > 
> > 
> > you mean openwrt overview page or clash overview page? i certainly have not experience this problem
> 
> OpenWrt overpage is fine. When you visit System > Startup, the page will not load. Both the Clash Dashboard and Yacd Dashboard are fine too. I've just deployed the new 18.06.4 image from scratch (openwrt-18.06.4-x86-64-combined-ext4) and just install the latest clash_0.15.0-1_x86_64 and luci-app-clash_0.24.0-1_all, when Clash is up and running, I can't get to the System > Startup page.
i also using openwrt-18.06.4-x86-64-combined and is working fine, no problem

**Comment by frainzy1477** [comment]
> > > When clash and luci-app-clash are running, the System > Startup page will not load, and the VM cannot be soft rebooted. No specific errors otherwise. OpenWrt 18.06.02 stock image + clash + luci-app-clash.
> > 
> > 
> > you mean openwrt overview page or clash overview page? i certainly have not experience this problem
> 
> OpenWrt overpage is fine. When you visit System > Startup, the page will not load. Both the Clash Dashboard and Yacd Dashboard are fine too. I've just deployed the new 18.06.4 image from scratch (openwrt-18.06.4-x86-64-combined-ext4) and just install the latest clash_0.15.0-1_x86_64 and luci-app-clash_0.24.0-1_all, when Clash is up and running, I can't get to the System > Startup page.

i also using openwrt-18.06.4-x86-64-combined and is working fine, no problem
