### ISSUE TITLE
对于大大提供的 Clash 预编译执行文件问题

### ISSUE THREAD

**Issue by laincat** [frainzy1477/clash#4]
> 主机型号	Netgear Nighthawk X4S R7800
> 架构	ARMv7 Processor rev 0 (v7l) x 2
> 固件版本	OpenWrt R9.4.18 By Lean / LuCI Master (git-19.115.08622-59e4954)
> 内核版本	4.14.113

目前路由系统如上，而您提供的好像没有 arm v7 的。

**Comment by frainzy1477** [comment]
是 aarch64?

**Comment by laincat** [comment]
大大你这个文件怎么编译？我想编译最新的 dev 版塞进去。。。

(我直接用 Clash 源的 make linux-armv7 编译出来的 bin 替换 /etc/clash/clash 文件，运行不了。。是编译需要什么额外参数？)

**Comment by frainzy1477** [comment]
我给你发的用不了？

**Comment by frainzy1477** [comment]
想用源的就改命名clash-linux-armv7到clash然后 替换/etc/clash/ 就行了。不需要 make . 如果不能启动运行命令
chmod +x /etc/clash/clash  
chmod +x /etc/init.d/clash

**Comment by laincat** [comment]
> 
> 
> 想用源的就改命名clash-linux-armv7到clash然后 替换/etc/clash/ 就行了。不需要 make . 如果不能启动运行命令
> chmod +x /etc/clash/clash
> chmod +x /etc/init.d/clash

好点，非常感激。
