### ISSUE TITLE
对yml/yaml内容顺序是否有要求？

### ISSUE THREAD

**Issue by NV3S** [frainzy1477/clash#40]
有两份配置在cfw都可以读取（不同api拉取的），但段落内的顺序不同（见图），图A加载后报错“did not find expected key”，图B正常。
请问是否存在这样顺序的要求？
![bc6399ba-7fee-4568-99f0-12981d713172](https://user-images.githubusercontent.com/17755534/60633250-5d2d7f80-9e3c-11e9-94a2-72376fe46900.jpg)
![cdfa0169-4bfc-42dc-94c7-bb29a2641c2a](https://user-images.githubusercontent.com/17755534/60633251-5dc61600-9e3c-11e9-9f87-8a4d9980436a.jpg)

**Comment by frainzy1477** [comment]
> 有两份配置在cfw都可以读取（不同api拉取的），但段落内的顺序不同（见图），图A加载后报错“did not find expected key”，图B正常。
> 请问是否存在这样顺序的要求？
> ![bc6399ba-7fee-4568-99f0-12981d713172](https://user-images.githubusercontent.com/17755534/60633250-5d2d7f80-9e3c-11e9-94a2-72376fe46900.jpg)
> ![cdfa0169-4bfc-42dc-94c7-bb29a2641c2a](https://user-images.githubusercontent.com/17755534/60633251-5dc61600-9e3c-11e9-9f87-8a4d9980436a.jpg)

看不懂
