### ISSUE TITLE
Cannot install package clash.

### ISSUE THREAD

**Issue by fbigun** [frainzy1477/clash#41]
不能安装，是否是不支持呢。

```
$opkg install clash_0.15.0-1_mipsel_24kc.ipk
Unknown package 'clash'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for clash found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package clash.

$cat /proc/cpuinfo
system type             : MediaTek MT7621
machine                 : Netgear R6220
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 581.63
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 581.63
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r2
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available
```

**Comment by jitdor** [comment]
你的硬件是MediaTek MT7621，这个是x86-64的啊

**Comment by frainzy1477** [comment]
> 不能安装，是否是不支持呢。
> 
> ```
> $opkg install clash_0.15.0-1_mipsel_24kc.ipk
> Unknown package 'clash'.
> Collected errors:
>  * pkg_hash_fetch_best_installation_candidate: Packages for clash found, but incompatible with the architectures configured
>  * opkg_install_cmd: Cannot install package clash.
> 
> $cat /proc/cpuinfo
> system type             : MediaTek MT7621
> machine                 : Netgear R6220
> processor               : 0
> cpu model               : MIPS 1004Kc V2.15
> BogoMIPS                : 581.63
> wait instruction        : yes
> microsecond timers      : yes
> tlb_entries             : 32
> extra interrupt vector  : yes
> hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
> isa                     : mips1 mips2 mips32r2
> ASEs implemented        : mips16 dsp mt
> shadow register sets    : 1
> kscratch registers      : 0
> core                    : 0
> VPE                     : 0
> VCED exceptions         : not available
> VCEI exceptions         : not available
> 
> processor               : 1
> cpu model               : MIPS 1004Kc V2.15
> BogoMIPS                : 581.63
> wait instruction        : yes
> microsecond timers      : yes
> tlb_entries             : 32
> extra interrupt vector  : yes
> hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
> isa                     : mips1 mips2 mips32r2
> ASEs implemented        : mips16 dsp mt
> shadow register sets    : 1
> kscratch registers      : 0
> core                    : 0
> VPE                     : 1
> VCED exceptions         : not available
> VCEI exceptions         : not available
> ```




> 不能安装，是否是不支持呢。
> 
> ```
> $opkg install clash_0.15.0-1_mipsel_24kc.ipk
> Unknown package 'clash'.
> Collected errors:
>  * pkg_hash_fetch_best_installation_candidate: Packages for clash found, but incompatible with the architectures configured
>  * opkg_install_cmd: Cannot install package clash.
> 
> $cat /proc/cpuinfo
> system type             : MediaTek MT7621
> machine                 : Netgear R6220
> processor               : 0
> cpu model               : MIPS 1004Kc V2.15
> BogoMIPS                : 581.63
> wait instruction        : yes
> microsecond timers      : yes
> tlb_entries             : 32
> extra interrupt vector  : yes
> hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
> isa                     : mips1 mips2 mips32r2
> ASEs implemented        : mips16 dsp mt
> shadow register sets    : 1
> kscratch registers      : 0
> core                    : 0
> VPE                     : 0
> VCED exceptions         : not available
> VCEI exceptions         : not available
> 
> processor               : 1
> cpu model               : MIPS 1004Kc V2.15
> BogoMIPS                : 581.63
> wait instruction        : yes
> microsecond timers      : yes
> tlb_entries             : 32
> extra interrupt vector  : yes
> hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
> isa                     : mips1 mips2 mips32r2
> ASEs implemented        : mips16 dsp mt
> shadow register sets    : 1
> kscratch registers      : 0
> core                    : 0
> VPE                     : 1
> VCED exceptions         : not available
> VCEI exceptions         : not available
> ```

试试这个 https://github.com/frainzy1477/clash/releases/download/v0.15.0/clash_0.15.0-1_mipsel_24kc_all.ipk

还有问题 运行命令 opkg print-architecture

**Comment by fbigun** [comment]
> 你的硬件是MediaTek MT7621，这个是x86-64的啊

我的这个不是 X86-64 吧。你是不是看错了。

**Comment by fbigun** [comment]
路由器不在身边，等待测试

**Comment by fbigun** [comment]
```
# opkg print-architecture
arch all 1
arch noarch 1
arch mipsel_24kc 10

# opkg install clash_0.15.0-1_mipsel_24kc_all.ipk
Package clash (0.15.0-1) installed in root is up to date.

# /etc/clash/clash
Illegal instruction
```
安装上去了，安装好后直接运行报错，装上`luci`也启动不了
@frainzy1477
