### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by brick713** [frainzy1477/clash#42]
runtime: this CPU has no VFPv3 floating point hardware, so it cannot run
this GOARM=7 binary. Recompile using GOARM=5 or GOARM=6.

**Comment by brick713** [comment]
arch all 1
arch noarch 1
arch arm_cortex-a15_neon-vfpv4 10

**Comment by frainzy1477** [comment]
> vfpv4
试试这个

https://github.com/frainzy1477/clash/releases/download/v0.15.0/clash_0.15.0-1_arm_cortex-a15_neon-vfpv4_armv5.ipk

还是这个

https://github.com/frainzy1477/clash/releases/download/v0.15.0/clash_0.15.0-1_arm_cortex-a15_neon-vfpv4_armv6.ipk
