### ISSUE TITLE
Cloud you please build mipsle 74kc ipk?

### ISSUE THREAD

**Issue by tianxiangkid** [frainzy1477/clash#44]
For saving some old router, thank you so much!!

**Comment by frainzy1477** [comment]
> For saving some old router, thank you so much!!

mipsle 74kc for what kind of router(model)

**Comment by tianxiangkid** [comment]
> > For saving some old router, thank you so much!!
> 
> mipsle 74kc for what kind of router(model)

Thx for reply~
Netgear wndr3700v4
I found v2ray-core_4.20.0-2_mips_24kc.ipk it can be installed,  So I believe mips 24kc also works~

**Comment by gitx6** [comment]
clash-linux-mips-softfloat. Try it.

**Comment by frainzy1477** [comment]
> > > For saving some old router, thank you so much!!
> > 
> > 
> > mipsle 74kc for what kind of router(model)
> 
> Thx for reply~
> Netgear wndr3700v4
> I found v2ray-core_4.20.0-2_mips_24kc.ipk it can be installed, So I believe mips 24kc also works~

试试这个 https://github.com/frainzy1477/clash/releases/download/v0.15.1-dev/clash_0.15.1-dev-ar71xx-nand_mips_24kc_softfloat.ipk

![image](https://user-images.githubusercontent.com/49537471/64163773-72db1780-ce74-11e9-9045-7c26b7d7310a.png)

**Comment by tianxiangkid** [comment]
> clash-linux-mips-softfloat. Try it.

It works

**Comment by tianxiangkid** [comment]
> > > > For saving some old router, thank you so much!!
> > > 
> > > 
> > > mipsle 74kc for what kind of router(model)
> > 
> > 
> > Thx for reply~
> > Netgear wndr3700v4
> > I found v2ray-core_4.20.0-2_mips_24kc.ipk it can be installed, So I believe mips 24kc also works~
> 
> 试试这个 https://github.com/frainzy1477/clash/releases/download/v0.15.1-dev/clash_0.15.1-dev-ar71xx-nand_mips_24kc_softfloat.ipk
> 
> ![image](https://user-images.githubusercontent.com/49537471/64163773-72db1780-ce74-11e9-9045-7c26b7d7310a.png)

T_T我自己拆包做了一个clash_0.15.1-dev-ar71xx-nand_mips_24kc_softfloat.ipk

**Comment by frainzy1477** [comment]
> 我自己拆包做了

好的
