### ISSUE TITLE
v0.15.1-dev的tar源码链接是多少？

### ISSUE THREAD

**Issue by Cakewalk598** [frainzy1477/clash#45]
为什么在v0.15.1-dev的源码链接下载的tar编译出来的是0.15.1，并不是v0.15.1-dev？是不是v0.15.1-dev的源码下载文件链接没更新？

**Comment by frainzy1477** [comment]
> 为什么在v0.15.1-dev的源码链接下载的tar编译出来的是0.15.1，并不是v0.15.1-dev？是不是v0.15.1-dev的源码下载文件链接没更新？

更新了   v0.15.2
https://github.com/frainzy1477/clash/releases/tag/v0.15.2

https://github.com/frainzy1477/clash_dev/releases/tag/v0.15.2
