### ISSUE TITLE
斐逊K3 Illegal instruction【clash_0.15.2_bcm53xx_arm_cortex-a9_armv7.ipk】

### ISSUE THREAD

**Issue by bzdouble** [frainzy1477/clash#47]
root@OpenWrt:/etc/clash# /etc/clash/clash -v
Illegal instruction
root@OpenWrt:/etc/clash# /etc/clash/clash -start
Illegal instruction
root@OpenWrt:/etc/clash# /etc/clash/clash -enable
Illegal instruction

--------------------------------------------
root@OpenWrt:/etc/clash# uname -a
Linux OpenWrt 4.14.94 #0 SMP Wed Jan 23 01:52:05 2019 armv7l GNU/Linux

--------------------------------------------
root@OpenWrt:/etc/clash# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 1400.00
Features        : half thumb fastmult edsp tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

processor       : 1
model name      : ARMv7 Processor rev 0 (v7l)
BogoMIPS        : 1400.00
Features        : half thumb fastmult edsp tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : BCM5301X
Revision        : 0000
Serial          : 0000000000000000

**Comment by frainzy1477** [comment]
> root@OpenWrt:/etc/clash# /etc/clash/clash -v
> Illegal instruction
> root@OpenWrt:/etc/clash# /etc/clash/clash -start
> Illegal instruction
> root@OpenWrt:/etc/clash# /etc/clash/clash -enable
> Illegal instruction
> 
> root@OpenWrt:/etc/clash# uname -a
> Linux OpenWrt 4.14.94 #0 SMP Wed Jan 23 01:52:05 2019 armv7l GNU/Linux
> 
> root@OpenWrt:/etc/clash# cat /proc/cpuinfo
> processor : 0
> model name : ARMv7 Processor rev 0 (v7l)
> BogoMIPS : 1400.00
> Features : half thumb fastmult edsp tls
> CPU implementer : 0x41
> CPU architecture: 7
> CPU variant : 0x3
> CPU part : 0xc09
> CPU revision : 0
> 
> processor : 1
> model name : ARMv7 Processor rev 0 (v7l)
> BogoMIPS : 1400.00
> Features : half thumb fastmult edsp tls
> CPU implementer : 0x41
> CPU architecture: 7
> CPU variant : 0x3
> CPU part : 0xc09
> CPU revision : 0
> 
> Hardware : BCM5301X
> Revision : 0000
> Serial : 0000000000000000

我用这gcc  https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic/openwrt-sdk-bcm53xx-generic_gcc-7.4.0_musl_eabi.Linux-x86_64.tar.xz   和  https://github.com/frainzy1477/clash_dev/releases/download/v0.15.2/clash-linux-armv7-v0.15.2.gz 编译

arm_cortex-a9 就是ARMv7-A architecture   https://openwrt.org/docs/techref/instructionset/arm_cortex-a9

如果有问题那我也不知道， 你先手动下载那个clash-linux-armv*-v0.15.2.gz可用然后我给你编译


![image](https://user-images.githubusercontent.com/49537471/64904638-4f7b5c80-d6ff-11e9-894e-7de6c1dc5533.png)

**Comment by bzdouble** [comment]
刚刚试了，也是Illegal instruction
我准备改固件了。

**Comment by frainzy1477** [comment]
> 刚刚试了，也是Illegal instruction
> 我准备改固件了。

应该是
  /etc/init.d/clash start   
还是
/etc/clash/clash  -d  /etc/clash/config.yaml
