### ISSUE TITLE
能否编译mips1400kc

### ISSUE THREAD

**Issue by NoColor2** [frainzy1477/clash#48]

**Comment by frainzy1477** [comment]
> _No description provided.
你的路由器品牌和型号

**Comment by NoColor2** [comment]
小米r3g

**Comment by frainzy1477** [comment]
> 小米r3g
你正在用是这个
https://downloads.openwrt.org/releases/18.06.1/targets/ramips/mt7621/openwrt-18.06.1-ramips-mt7621-mir3g-squashfs-rootfs0.bin
和
https://downloads.openwrt.org/releases/18.06.1/targets/ramips/mt7621/openwrt-18.06.1-ramips-mt7621-mir3g-squashfs-kernel1.bin

？？？

**Comment by NoColor2** [comment]
是的

**Comment by frainzy1477** [comment]
> 是的

试试这个  https://github.com/frainzy1477/clash/releases/download/v0.15.2/clash_0.15.2_ramips_mt7621_mipsel_24kc.ipk

**Comment by NoColor2** [comment]
成功运行，谢谢
