### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by RealKiro** [frainzy1477/clash#49]
没有找到 https://sources.openwrt.org/clash-linux-mipsle-v0.15.2.gz ，编译出错
![image](https://user-images.githubusercontent.com/33367701/65010477-8beaca80-d942-11e9-875b-08bf3828fee8.png)
---
MTK7621 Newifi3

**Comment by frainzy1477** [comment]
> ## 没有找到 https://sources.openwrt.org/clash-linux-mipsle-v0.15.2.gz ，编译出错
> ![image](https://user-images.githubusercontent.com/33367701/65010477-8beaca80-d942-11e9-875b-08bf3828fee8.png)
> MTK7621 Newifi3

你要修改Makefile吧， 你在用是x86或者arm

用这个  https://github.com/frainzy1477/clash/tree/mips/mipsel
