### ISSUE TITLE
 sh: bash: not found 运行报错

### ISSUE THREAD

**Issue by lwsJ** [frainzy1477/clash#5]
请教一下，以下两个文件（clash_0.14.0_mipsel_24kc.ipk  luci-app-clash_2.2b-1_all.ipk）都正确安装了，运行clash时 日志显示  sh: bash: not found  这个是什么原因呢？路由器是MT7620A的主控，openwrt18.06.2 版。谢谢！

**Comment by frainzy1477** [comment]
你必须要安装bash， 现在更新到2.3

**Comment by frainzy1477** [comment]
> 请教一下，以下两个文件（clash_0.14.0_mipsel_24kc.ipk luci-app-clash_2.2b-1_all.ipk）都正确安装了，运行clash时 日志显示 sh: bash: not found 这个是什么原因呢？路由器是MT7620A的主控，openwrt18.06.2 版。谢谢！

你必须要安装bash， 现在更新到2.3

**Comment by lwsJ** [comment]
有下载地址吗？

**Comment by lwsJ** [comment]
或者说如何安装，抱歉，小白摸索中，谢谢！

**Comment by lwsJ** [comment]
已经安装好了
