### ISSUE TITLE
安装Luci for Clash ipk之后dhcp无法正常工作

### ISSUE THREAD

**Issue by whoshoe** [frainzy1477/clash#50]
我在openwrt snapshot上安装Luci for Clash的ipk过程中提示错误，然后先把dnsmasq卸载了之后才安装成功。之后重启路由发现dhcp无法正常工作了，所有连接路由的设备都没有分配ip地址。重新设置了/etc/config/dhcp也无法解决。

**Comment by frainzy1477** [comment]
> 我在openwrt snapshot上安装Luci for Clash的ipk过程中提示错误，然后先把dnsmasq卸载了之后才安装成功。之后重启路由发现dhcp无法正常工作了，所有连接路由的设备都没有分配ip地址。重新设置了/etc/config/dhcp也无法解决。

等v1.1.1吧， 重新编译并移除依赖项
