### ISSUE TITLE
关于“走代理的局域网IP”功能问题

### ISSUE THREAD

**Issue by shikkoku** [frainzy1477/clash#51]
我开启该功能后，只有选定的IP主机可以正常上网，其余设备完全不能上网，包括访问百度等国内网站。使用默认的fake-ip模式。

**Comment by frainzy1477** [comment]
> 我开启该功能后，只有选定的IP主机可以正常上网，其余设备完全不能上网，包括访问百度等国内网站。使用默认的fake-ip模式。

最新的 Clash内核 走/不走代理的局域网IP功能都不支持fake-ip, 你可以加一个规则SRC-IP-CIDR,192.168.1.2/31,DIRECT / Proxy

**Comment by shikkoku** [comment]
感谢告知，我还是用回`REDIR-HOST`吧，虽然理论性能会差点。用`REDIR-HOST`配好DNS后界面上的淘宝IP检测不会闪来闪去了……
