### ISSUE TITLE
新版clash在lean源码编译后无法运行启动

### ISSUE THREAD

**Issue by Cakewalk598** [frainzy1477/clash#53]
新版clash0.15.4 以及luci-app-clash 1.1.2在lean源码编译后的固件上点击启动后无法运行启动。

**Comment by frainzy1477** [comment]
> 新版clash0.15.4 以及luci-app-clash 1.1.2在lean源码编译后的固件上点击启动后无法运行启动。

我也用lean源码编译没有问题

**Comment by frainzy1477** [comment]
更新了
