### ISSUE TITLE
最新版clash以及最新版界面文件问题反馈

### ISSUE THREAD

**Issue by Cakewalk598** [frainzy1477/clash#54]
0.15.4 ，1.1.3 ，在官方源码以及lean源码编译出的固件全部无法启动运行。

**Comment by frainzy1477** [comment]
> 0.15.4 ，1.1.3 ，在官方源码以及lean源码编译出的固件全部无法启动运行。

我用一样源码编译了没有问题哦

试试这个。直接从我的电脑上传 。如果还有问题呢我没有办法  https://github.com/frainzy1477/luci-app-clash/releases/download/v1.1.3/luci-app-clash.zip

**Comment by shikkoku** [comment]
> > 0.15.4 ，1.1.3 ，在官方源码以及lean源码编译出的固件全部无法启动运行。
> 
> 我用一样源码编译了没有问题哦
> 
> 试试这个。直接从我的电脑上传 。如果还有问题呢我没有办法 https://github.com/frainzy1477/luci-app-clash/releases/download/v1.1.3/luci-app-clash.zip

请您更新您的固件源码。您的LuCI Master版本没有同步。

OpenWrt R9.10.1 / LuCI Master (git-19.268.50099-562a894)

**Comment by frainzy1477** [comment]
> > > 0.15.4 ，1.1.3 ，在官方源码以及lean源码编译出的固件全部无法启动运行。
> > 
> > 
> > 我用一样源码编译了没有问题哦
> > 试试这个。直接从我的电脑上传 。如果还有问题呢我没有办法 https://github.com/frainzy1477/luci-app-clash/releases/download/v1.1.3/luci-app-clash.zip
> 
> 请您更新您的固件源码。您的LuCI Master版本没有同步。
> 
> OpenWrt R9.10.1 / LuCI Master (git-19.268.50099-562a894)

好的，周末试试

**Comment by shikkoku** [comment]
自lean大更新luci库后，固件自带的某些功能选项也是没法生效，等修。

**Comment by frainzy1477** [comment]
> 自lean大更新luci库后，固件自带的某些功能选项也是没法生效，等修。

更新了

**Comment by shikkoku** [comment]
> > 自lean大更新luci库后，固件自带的某些功能选项也是没法生效，等修。
> 
> 更新了

除了主页面的淘宝状态老是在timeout和NORMAL来回切换（老问题 ），其余功能看上去已经正常工作。

**Comment by frainzy1477** [comment]
> > > 自lean大更新luci库后，固件自带的某些功能选项也是没法生效，等修。
> > 
> > 
> > 更新了
> 
> 除了主页面的淘宝状态老是在timeout和NORMAL来回切换（老问题 ），其余功能看上去已经正常工作。

淘宝状态的问题是CORS的问题有时候这一样

**Comment by gitx6** [comment]
昨天吧lean版错误安装在旧luci，好像也可以工作。没做详细测试，仅供参考。

**Comment by frainzy1477** [comment]
> 昨天吧lean版错误安装在旧luci，好像也可以工作。没做详细测试，仅供参考。

应该可以在旧luci工作啊， 以前我用是这一样但有人不能在旧luci单击按钮用所以修改了.

**Comment by gitx6** [comment]
我的意思是可以不用维护两个版本
