### ISSUE TITLE
请问树莓派3B 要用哪个包？

### ISSUE THREAD

**Issue by doreencheng** [frainzy1477/clash#55]
请问树莓派3B刷的openwrt要用哪个包，试了几个安装都显示架构不匹配。

设备型号 | Raspberry Pi 3 Model B Rev 1.2
架构 | ARMv7 Processor rev 4 (v7l) x 4
固件版本 | OpenWrt R9.9.15 / LuCI Master (git-19.265.58015-b31beb5)
内核版本 | 4.19.72

**Comment by frainzy1477** [comment]
> 请问树莓派3B刷的openwrt要用哪个包，试了几个安装都显示架构不匹配。
> 
> 设备型号 | Raspberry Pi 3 Model B Rev 1.2
> 架构 | ARMv7 Processor rev 4 (v7l) x 4
> 固件版本 | OpenWrt R9.9.15 / LuCI Master (git-19.265.58015-b31beb5)
> 内核版本 | 4.19.72

先试试armv7的
https://github.com/frainzy1477/clash/releases/download/v0.15.4/clash_0.15.4_brcm2807_arm_arm1176jzf-s_vfp_ras_pi_armv7.ipk

https://github.com/frainzy1477/clash/releases/download/v0.15.4/clash_0.15.4_brcm2807_arm_arm1176jzf-s_vfp_ras_pi_armv6.ipk

https://github.com/frainzy1477/clash/releases/download/v0.15.4/clash_0.15.4_brcm2807_arm_arm1176jzf-s_vfp_ras_pi_armv8.ipk

**Comment by doreencheng** [comment]
`root@pi:~# opkg install clash_0.15.4_brcm2807_arm_arm1176jzf-s_vfp_ras_pi_armv7.ipk
Unknown package 'clash'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for clash found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package clash.`

试过，都是显示这个错误。

**Comment by frainzy1477** [comment]
> root@pi:~# opkg install clash_0.15.4_brcm2807_arm_arm1176jzf-s_vfp_ras_pi_armv7.ipk
> Unknown package 'clash'.
> Collected errors:
> 
> * pkg_hash_fetch_best_installation_candidate: Packages for clash found, but incompatible with the architectures configured
> * opkg_install_cmd: Cannot install package clash.
> 
> 试过，都是显示这个错误。

运行  opkg print-architecture 吧输出来

**Comment by doreencheng** [comment]
6 7和 8一样的错误，树莓派3B应该是V7。

root@pi:~# opkg print-architecture
arch all 1
arch noarch 1
arch arm_cortex-a7_neon-vfpv4 10

root@pi:~# opkg status libc 2>/dev/null |grep 'Architecture' |awk -F ': ' '{print $2}'
arm_cortex-a7_neon-vfpv4

**Comment by frainzy1477** [comment]
> 6 7和 8一样的错误，树莓派3B应该是V7。
> 
> root@pi:~# opkg print-architecture
> arch all 1
> arch noarch 1
> arch arm_cortex-a7_neon-vfpv4 10
> 
> root@pi:~# opkg status libc 2>/dev/null |grep 'Architecture' |awk -F ': ' '{print $2}'
> arm_cortex-a7_neon-vfpv4

你试试
https://github.com/frainzy1477/clash/releases/download/v0.15.4/clash_0.15.4_brcm2708-bcm2709-arm_cortex-a7_neon-vfpv4_ras_pi_armv7.ipk

**Comment by doreencheng** [comment]
> > 6 7和 8一样的错误，树莓派3B应该是V7。
> > root@pi:~# opkg print-architecture
> > arch all 1
> > arch noarch 1
> > arch arm_cortex-a7_neon-vfpv4 10
> > root@pi:~# opkg status libc 2>/dev/null |grep 'Architecture' |awk -F ': ' '{print $2}'
> > arm_cortex-a7_neon-vfpv4
> 
> 你试试
> https://github.com/frainzy1477/clash/releases/download/v0.15.4/clash_0.15.4_brcm2708-bcm2709-arm_cortex-a7_neon-vfpv4_ras_pi_armv7.ipk

这个可以了，感谢！
