### ISSUE TITLE
dns设置有问题

### ISSUE THREAD

**Issue by Cakewalk598** [frainzy1477/clash#56]
访问控制功能有问题，不走代理的IP列表：选择LAN IP只不走代理 ，这里设置步骤IP代理的设备后，导致NAS设备的DNS出现错误，并且远程无法打开NAS管理页面，也就是访问控制功能无法控制IP步骤代理。

**Comment by frainzy1477** [comment]
> 访问控制功能有问题，不走代理的IP列表：选择LAN IP只不走代理 ，这里设置步骤IP代理的设备后，导致NAS设备的DNS出现错误，并且远程无法打开NAS管理页面，也就是访问控制功能无法控制IP步骤代理。

不支持fake-ip

**Comment by Cakewalk598** [comment]
> 
> 
> > 访问控制功能有问题，不走代理的IP列表：选择LAN IP只不走代理 ，这里设置步骤IP代理的设备后，导致NAS设备的DNS出现错误，并且远程无法打开NAS管理页面，也就是访问控制功能无法控制IP步骤代理。
> 
> 不支持fake-ip

那要怎样调成不是fake-ip模式？

**Comment by shikkoku** [comment]
> > > 访问控制功能有问题，不走代理的IP列表：选择LAN IP只不走代理 ，这里设置步骤IP代理的设备后，导致NAS设备的DNS出现错误，并且远程无法打开NAS管理页面，也就是访问控制功能无法控制IP步骤代理。
> > 
> > 
> > 不支持fake-ip
> 
> 那要怎样调成不是fake-ip模式？

https://github.com/frainzy1477/luci-app-clash/wiki/Redir-Host-Mode

启用自定义DNS设置项里修改。

fake-ip搞起来麻烦，似乎不能只指定内网某几台主机走规则代理，其余主机不走代理。不走代理的要全部填规则很麻烦的样子。

**Comment by frainzy1477** [comment]
enhanced-mode: redir-host

![image](https://user-images.githubusercontent.com/49537471/65811676-b8c69980-e1ee-11e9-96aa-99974fc812a4.png)

**Comment by frainzy1477** [comment]
> > > 访问控制功能有问题，不走代理的IP列表：选择LAN IP只不走代理 ，这里设置步骤IP代理的设备后，导致NAS设备的DNS出现错误，并且远程无法打开NAS管理页面，也就是访问控制功能无法控制IP步骤代理。
> > 
> > 
> > 不支持fake-ip
> 
> 那要怎样调成不是fake-ip模式？

enhanced-mode: redir-host

![image](https://user-images.githubusercontent.com/49537471/65811676-b8c69980-e1ee-11e9-96aa-99974fc812a4.png)

**Comment by Cakewalk598** [comment]
按照你的方法修改自定义DNS后访问控制IP正常控制了，谢谢。

frainzy1477 <notifications@github.com> 于2019年9月28日周六 下午12:52写道：
