### ISSUE TITLE
Gateway timeout

### ISSUE THREAD

**Issue by ichswarox** [frainzy1477/clash#57]
<img width="1139" alt="Screen Shot 2019-10-11 at 10 01 16 AM" src="https://user-images.githubusercontent.com/18469758/66619097-3b4b5200-ec0e-11e9-97f8-d258704aabe9.png">
I get this error message, and I can't use my proxy server, it is function well on my Mac

**Comment by frainzy1477** [comment]
You need to check your configuration, highly possible there is wrong entry
