### ISSUE TITLE
Clash控制面板按钮在bootstrap主题下为按钮与文字均为白色无法识别

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#6]
使用openwrt缺省的luci-theme-bootstrap主题下按钮和文字均为白色无法识别。可否改底色为蓝色；或者文字为黑色。
![主题](https://user-images.githubusercontent.com/24645789/58372919-ca094c00-7f57-11e9-9887-a917bebae0ba.JPEG)

**Comment by frainzy1477** [comment]
> 使用openwrt缺省的luci-theme-bootstrap主题下按钮和文字均为白色无法识别。可否改底色为蓝色；或者文字为黑色。
> ![主题](https://user-images.githubusercontent.com/24645789/58372919-ca094c00-7f57-11e9-9887-a917bebae0ba.JPEG)

一会修改吧

**Comment by frainzy1477** [comment]
> 使用openwrt缺省的luci-theme-bootstrap主题下按钮和文字均为白色无法识别。可否改底色为蓝色；或者文字为黑色。
> ![主题](https://user-images.githubusercontent.com/24645789/58372919-ca094c00-7f57-11e9-9887-a917bebae0ba.JPEG)
https://github.com/frainzy1477/clash/releases/download/v2.3/luci-app-clash_2.3_bootstrap-1_all.ipk
