### ISSUE TITLE
请看图请求解决

### ISSUE THREAD

**Issue by denel23** [frainzy1477/clash#60]
![1572186261202](https://user-images.githubusercontent.com/31842977/67636302-3f63b900-f90a-11e9-8eeb-b79bdcde08fc.jpg)
![1572186254455](https://user-images.githubusercontent.com/31842977/67636306-4a1e4e00-f90a-11e9-8072-026e24bc0a03.jpg)
![1572186287246](https://user-images.githubusercontent.com/31842977/67636310-4be81180-f90a-11e9-804a-4c86c23354c0.jpg)
第二图是clash内部log，三图是路由器系统日志。。
这样要怎么解决，大佬们帮忙。万分感谢

**Comment by frainzy1477** [comment]
运行ssh命令:    service clash stop
