### ISSUE TITLE
一段时间出现dial Proxy error: server ip:prot connect error: dial tcp4 server ip:port: i/o timeout

### ISSUE THREAD

**Issue by denel23** [frainzy1477/clash#61]
这样如何解决？

**Comment by frainzy1477** [comment]
这是你的dns问题还是你的服务器问题

**Comment by Neubulae** [comment]
dial Proxy error: server ip:port connect error: dial tcp4 server ip:port: i/o timeout
标题中间的ip和port是SS的ip和端口, 如果使用的是Vmess的化会提示connection error

**Comment by frainzy1477** [comment]
用cfw没有问你题？

**Comment by Neubulae** [comment]
我试试看先

**Comment by Neubulae** [comment]
试着ping了一下那个服务器，丢包率特别高，会不会是这个原因

**Comment by Neubulae** [comment]
顺便，这个帖子的问题应该是Vultr服务器出问题了

**Comment by frainzy1477** [comment]
是服务器问题。
谷歌上不了Youtube上不了，使用firefox看看， chrome有时候这一样

**Comment by Neubulae** [comment]
显示的是NXDomain…但我的DNS看上去没有问题

**Comment by denel23** [comment]
发现是服务器问题，特别是晚上9点后延迟高了。换了其他节点就好了

**Comment by denel23** [comment]
两次低级失误提问很抱歉，现在关闭。
