### ISSUE TITLE
关于日志显示只能解析ip地址的问题

### ISSUE THREAD

**Issue by chocksyu** [frainzy1477/clash#7]
您好！
    抱歉又遇到了新的问题。
    完全按照您的方案在pi上重新部署了一下，但是在日志中发现只有ip地址，没有域名。这样就导致clash里设置的一些规则策略无法使用，请问如何解决？

**Comment by vernesong** [comment]
#5

**Comment by frainzy1477** [comment]
> 您好！
> 抱歉又遇到了新的问题。
> 完全按照您的方案在pi上重新部署了一下，但是在日志中发现只有ip地址，没有域名。这样就导致clash里设置的一些规则策略无法使用，请问如何解决？

https://github.com/frainzy1477/clash/releases/tag/v0.13.0_1
新编译了
