### ISSUE TITLE
yacd控制面板无法logout，修改控制端口和密码

### ISSUE THREAD

**Issue by gitx6** [frainzy1477/clash#7]
yacd 控制面板无法 logout，修改控制端口和密码。点击 config-logout，页面保持原样。

使用 clash 控制面板或者外部 http://yacd.haishan.me 的控制面板没有问题

**Comment by frainzy1477** [comment]
> yacd 控制面板无法 logout，修改控制端口和密码。点击 config-logout，页面保持原样。
> 
> 使用 clash 控制面板或者外部 http://yacd.haishan.me 的控制面板没有问题
![image](https://user-images.githubusercontent.com/49537471/58373125-97f9e900-7f5b-11e9-89e4-1385ca5e530e.png)

![image](https://user-images.githubusercontent.com/49537471/58373136-bd86f280-7f5b-11e9-9e9a-d2ee405d01ba.png)


我自己没有问题

**Comment by gitx6** [comment]
升级到最新 luci，尝试了 Mac OS 下的两个浏览器均有问题
Safari 11.1.2 - 无法 logout，修改地址／端口／密码
Chrome  71.0.3578.98 - 无法登陆。停留在地址／端口／密码页面

**Comment by gitx6** [comment]
/etc/config/uhttpd 删除 443 端口那两段，重启

改 https 为 http 方式登陆，问题解决。
