### ISSUE TITLE
2. Services  ----        选择进去不显示

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#8]
----------------------------------------------------------------------------------------------------------------------+ |
  | |                                                    1. Collections  --->                                                                                              | |
  | |                                                    2. Modules  --->                                                                                                  | |
  | |                                                    2. Services  ----                                                                                                 | |
  | |                                                    3. Applications  --->                                                                                             | |
  | |                                                    4. Themes  --->                                                                                                   | |
  | |                                                    5. Protocols  --->                                                                                                | |
  | |                                                    6. Libraries  --->                                                                                                | |
  | |                                                    9. Freifunk  --->                                                                                                 | |
  | |                                                                                                                                                                      | |
  | |                                                                                                                                                                      | |
  | |

**Comment by frainzy1477** [comment]
> ----------------------------------------------------------------------------------------------------------------------+ |
> | | 1. Collections ---> | |
> | | 2. Modules ---> | |
> | | 2. Services ---- | |
> | | 3. Applications ---> | |
> | | 4. Themes ---> | |
> | | 5. Protocols ---> | |
> | | 6. Libraries ---> | |
> | | 9. Freifunk ---> | |
> | | | |
> | | | |
> | |

没有什么问题
![Screenshot_1](https://user-images.githubusercontent.com/49537471/58567264-a2bac380-8264-11e9-83b2-04b1993568b3.png)
