### ISSUE TITLE
config.yml是否有标准格式，墙洞机场的订阅提示错误的的格式

### ISSUE THREAD

**Issue by zcracker** [frainzy1477/clash#9]
config.yml是否有标准格式，墙洞机场的订阅提示错误的的格式，是否方便提供一个模板

**Comment by frainzy1477** [comment]
> config.yml

如果你知道怎么写clash config.yml 那就行了。都是标准格式，我不知道你们哪里有问题
config.yml 可以写dreamco 的 https://github.com/Dreamacro/clash/tree/master

**Comment by zcracker** [comment]
nohup: failed to run command ‘/etc/clash/clash’: Exec format error 什么错误呢

**Comment by zcracker** [comment]
system type             : Atheros AR9344 rev 2
machine                 : NETGEAR WNDR4300
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 278.93
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available
是不是不支持呢

**Comment by zcracker** [comment]
ifeq ($(ARCH),mipsel)
	PKG_ARCH:=mipsle
endif
ifeq ($(ARCH),mips)
	PKG_ARCH:=mips64
endif
ifeq ($(ARCH),i386)
	PKG_ARCH:=386
endif
ifeq ($(ARCH),x86_64)
	PKG_ARCH:=amd64
endif
ifeq ($(ARCH),arm)
	PKG_ARCH:=armv6
endif
ifeq ($(ARCH),aarch64)
	PKG_ARCH:=armv8

**Comment by frainzy1477** [comment]
> MIPS 74Kc V4.12

MIPS 74Kc V4.12 不知道是不是mips soft的
![image](https://user-images.githubusercontent.com/49537471/58652369-f81ad180-8345-11e9-8133-ae7b8c8c89d1.png)
去试试吧

**Comment by wangxin6** [comment]
#1  有编译好的版本可以去测试。

我最近太忙，没有时间在路由器上测试。有结果请告知。谢谢。

**Comment by gitx6** [comment]
IPK文件如何编译？

**Comment by zcracker** [comment]
clash的Makefile文件里面好像没有这个，仅仅支持以下cpu
ifeq ($(ARCH),mipsel)
PKG_ARCH:=mipsle
endif
ifeq ($(ARCH),mips)
PKG_ARCH:=mips64
endif
ifeq ($(ARCH),i386)
PKG_ARCH:=386
endif
ifeq ($(ARCH),x86_64)
PKG_ARCH:=amd64
endif
ifeq ($(ARCH),arm)
PKG_ARCH:=armv6
endif
ifeq ($(ARCH),aarch64)
PKG_ARCH:=armv8

**Comment by frainzy1477** [comment]
> clash的Makefile文件里面好像没有这个，仅仅支持以下cpu
> ifeq ($(ARCH),mipsel)
> PKG_ARCH:=mipsle
> endif
> ifeq ($(ARCH),mips)
> PKG_ARCH:=mips64
> endif
> ifeq ($(ARCH),i386)
> PKG_ARCH:=386
> endif
> ifeq ($(ARCH),x86_64)
> PKG_ARCH:=amd64
> endif
> ifeq ($(ARCH),arm)
> PKG_ARCH:=armv6
> endif
> ifeq ($(ARCH),aarch64)
> PKG_ARCH:=armv8

你可以修改Makefile

**Comment by zcracker** [comment]
硬件分类搞不清楚，不知道怎么该啊，烦请大佬修改

**Comment by frainzy1477** [comment]
> 硬件分类搞不清楚，不知道怎么该啊，烦请大佬修改

运行此命令然后给我看看

opkg print-architecture

**Comment by zcracker** [comment]
arch all 1
arch noarch 1
arch mips_24kc 10

**Comment by zcracker** [comment]
root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch mips_24kc 10

**Comment by zcracker** [comment]
root@OpenWrt:~# cat /proc/cpuinfo 
system type             : Atheros AR9344 rev 2
machine                 : NETGEAR WNDR4300
processor               : 0
cpu model               : MIPS 74Kc V4.12
BogoMIPS                : 278.93
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa                     : mips1 mips2 mips32r1 mips32r2
ASEs implemented        : mips16 dsp dsp2
shadow register sets    : 1
kscratch registers      : 0
package                 : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by zcracker** [comment]
ifeq ($(ARCH),arm)
PKG_ARCH:=armv7
endif
老大加一行这个吧   mips_24kc准备弃了

**Comment by frainzy1477** [comment]
> ifeq ($(ARCH),arm)
> PKG_ARCH:=armv7
> endif
> 老大加一行这个吧 mips_24kc准备弃了

现在好了吗?

**Comment by frainzy1477** [comment]
> ifeq ($(ARCH),arm)
> PKG_ARCH:=armv7
> endif
> 老大加一行这个吧 mips_24kc准备

已经有V6你自己在编译ipk可以改到V7

**Comment by zcracker** [comment]
root@OpenWrt:~# opkg print-architecture
arch all 1
arch noarch 1
arch arm_cortex-a9_vfpv3 10
root@OpenWrt:~# cat /proc/cpu
cpu/     cpuinfo
root@OpenWrt:~# cat /proc/cpuinfo 
processor       : 0
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 1600.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

processor       : 1
model name      : ARMv7 Processor rev 1 (v7l)
BogoMIPS        : 1600.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x4
CPU part        : 0xc09
CPU revision    : 1

Hardware        : Marvell Armada 380/385 (Device Tree)
Revision        : 0000
Serial          : 0000000000000000
